AWSTemplateFormatVersion: "2010-09-09"

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub mattermost/${AWS::StackName}
      RetentionInDays: 7

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: mathieu.brochard@capgemini.com
          Protocol: email

Outputs:
  LogGroupName:
    Value: !Ref LogGroup

  AlarmTopicArn:
    Value: !Ref AlarmTopic
