name: Deploy in development environment

on:
  pull_request:
  merge_group:

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-rain-cli

      - uses: ./.github/actions/configure-aws-credentials

      - name: Deploy CloudFormation stack
        run: rain deploy -y main.yaml mattermost-${{ github.head_ref }}
